name: Release with tag = version from API spec (or abort if already tagged), then call provided publish command

on:
  workflow_call:
    inputs:
      api-spec-json:
        description: Open API specification file in json - version is used to tag, release and publish.
        type: string
        required: true
      publish-command:
        description: Command to publish artifacts (npm publish, mvn deploy, both, or some other strange command).
        type: string
        required: true
      # Little reason to override inputs below:
      # no code should be compiled or run with proper use of workflow
      # auth is default GITHUB_TOKEN, so github packages will work, other registries might balk
      npm-registry-url:
        description: npm registry to publish to
        type: string
        default: https://npm.pkg.github.com
      node-version:
        description: Node version used
        type: string
        default: '24'
      java-version:
        description: Java version used
        type: string
        default: '25'
      java-distribution:
        description: Java distribution used
        type: string
        default: 'temurin'
    outputs:
      version:
        description: version tagged, released and published
        value: ${{ jobs.versioning.outputs.version }}
      release:
        description: true if a release was created and artifacts published
        value: ${{ jobs.versioning.outputs.release }}

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.apiversion.outputs.apiversion }}
      release: ${{ steps.goahead.outputs.release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find last release tag
        id: gitversion
        run: |
          git fetch --tags
          LAST_GIT_TAG=$(git tag --sort=-v:refname | head -n1)
          if [ -z "$LAST_GIT_TAG" ]; then
            LAST_RELEASE_VERSION="0.0.0"
          else
            LAST_RELEASE_VERSION=$(echo "$LAST_GIT_TAG" | awk -F. '{print $1 "." $2 "." $3+1}')
          fi
          echo "gitversion=$LAST_RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Find package.json version
        id: apiversion
        run: |
          API_VERSION=$( jq -er '.info.version' ${{ inputs.api-spec-json }} )
          if [ -z "$API_VERSION" ] || [ "$API_VERSION" = "{}" ]; then
            echo "::error::Could not read version from {{ inputs.api-spec-json }}"
            exit 1
          fi
          echo "apiversion=$API_VERSION" >> $GITHUB_OUTPUT

      - name: Determine need for release by comparing package.json version to last git version tag, abort if they are the same
        id: goahead
        run: |
          if [ "${{ steps.apiversion.outputs.apiversion }}" = "${{ steps.gitversion.outputs.gitversion }}" ]; then
            echo "::info::Terminate release because package.json version ${{ steps.apiversion.outputs.apiversion }} is same as git version ${{ steps.gitversion.outputs.gitversion }}."
            echo "release=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "release=true" >> "$GITHUB_OUTPUT"


  release:
    runs-on: ubuntu-latest
    needs: [ versioning ]
    permissions:
      contents: write
    if: needs.versioning.outputs.release == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.versioning.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish:
    runs-on: ubuntu-latest
    needs: [ versioning ]
    permissions:
      contents: write
      packages: write
    if: needs.versioning.outputs.release == 'true'
    outputs:
      published: ${{ steps.publish.outputs.published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: # node is preinstalled on ubuntu-latest, but publish needs setup-node to configure registry and auth
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.npm-registry-url }}
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
      - name: Publish artifacts
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ${{ inputs.publish-command }}
