name: Align Open API version across project, commit and push any updated files

on:
  workflow_call:
    inputs:
      align-command:
        description: Command to align Open API version across project (get project ready to publish).
        type: string
        required: true
      commit-message:
        description: Commit message for the changes made by the align command.
        type: string
        default: 'chore: update API spec'

jobs:
  update-spec:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: update
        run: |
          ${{ inputs.align-command }}
          git status
          git add -A

      - name: Commit changes
        uses: statens-pensjonskasse/gha-create-signed-commit@2343535e0ab61d4bd30954ca59d1fb66f1d85c51 # v0.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ inputs.commit-message }}
          fail-on-no-changes: false
          push: true
