name: Update Open API specification
# run npm update-spec, commit and push changes, in case developer / renovate forgets

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  update-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - name: update
        run: |
          npm run update-spec
          git add -A

      - name: Commit changes
        uses: statens-pensjonskasse/gha-create-signed-commit@2343535e0ab61d4bd30954ca59d1fb66f1d85c51 # v0.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: update API spec'
          fail-on-no-changes: false
          push: true
