name: Update project files after changes to API (version) / before publising

on:
  push:
    branches:
      - '**'

jobs:
  update-spec:
    uses: statens-pensjonskasse/skatt-inntekt-api/.github/workflows/api-prepare.yml@5bebe21e5e77aa7e6f56be5ea683552591554a9e
    with:
      align-command: 'npm ci && npm run update-spec'
      commit-message: 'chore: update of API carried to other project files'
    permissions:
      contents: write
    secrets: inherit
