name: Tag a release and publish artifacts if needed

on:
  push:
    branches:
      - '**'


concurrency:
  group: renovate-api
  cancel-in-progress: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.21.0
          registry-url: https://npm.pkg.github.com
          scope: '@statens-pensjonskasse'

      - name: update
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: |
          npm install # ci is useless on a renovate PR
          npm run update-spec
          git status
          git add -A

      - name: Commit changes
        uses: statens-pensjonskasse/gha-create-signed-commit@7b9e477ae72b66627fb37db6b841f0e31d3d965e # v0.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: update API spec'
          fail-on-no-changes: false
          push: true

  publish:
    if: github.ref == 'refs/heads/main'
    uses: statens-pensjonskasse/openapi-artifact-wrapper/.github/workflows/api-publish.yml@e944a0ff199a8fb7da27999951b622f815538bcc  # 0.0.4
    with:
      api-spec-json: skatt-inntekt-api.json
      publish-command: npm publish && npm run mvn-publish
    permissions:
      contents: write
      packages: write
    secrets: inherit
