name: Run update script and - if appropriate - tag a release and publish artifacts

on:
  push:
    branches:
      - '**'

concurrency:
  group: release-and-publish
  cancel-in-progress: false

jobs:
  update-spec:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version: 24.21.0
          registry-url: https://npm.pkg.github.com
          scope: '@statens-pensjonskasse'

      - name: update
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: |
          npm install # ci is useless on a renovate PR
          npm run update-spec
          git status
          git add -A

      - name: Commit changes
        uses: statens-pensjonskasse/gha-create-signed-commit@7b9e477ae72b66627fb37db6b841f0e31d3d965e # v0.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: update API spec'
          fail-on-no-changes: false
          push: true

  release:
    if: github.ref == 'refs/heads/main'
    uses: statens-pensjonskasse/openapi-artifact-wrapper/.github/workflows/api-release.yml@b8dfe0bb64ab1fc0239c36b7d735dbc47c42fdc8  # 0.0.5
    with:
      api-spec-json: skatt-inntekt-api.json
    permissions:
      contents: write
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: false # needs.release.outputs.release-performed == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with: # node is preinstalled on ubuntu-latest, but publish needs setup-node to configure registry and auth
          node-version: 24.21.0
          registry-url: https://npm.pkg.github.com
          scope: '@statens-pensjonskasse'
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          java-version: 25
          distribution: temurin
      - name: Publish artifacts
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_FOR_PACKAGES_ACCESS || secrets.GITHUB_TOKEN }} # node may need to install a package
          GITHUB_TOKEN: ${{ github.token }} # maven should have no dependencies
        run: |
          npm ci
          npm publish
          npm run mvn-publish
