name: Tag a release and publish artifacts if needed

on:
  push:
    branches:
      - main

jobs:
  release-publish:
    uses: statens-pensjonskasse/skatt-inntekt-api/.github/workflows/api-publish.yml@5bebe21e5e77aa7e6f56be5ea683552591554a9e
    with:
      api-spec-json: 'skatt-inntekt-api.json'
      publish-command: 'npm publish'
    permissions:
      contents: write
      packages: write
    secrets: inherit
