name: Tag a release and publish artifacts if needed

on:
  push:
    branches:
      - main

jobs:
  release-publish:
    uses: api-publish.yml
    with:
      api-spec-json: 'skatt-inntekt-api.json'
      publish-command: 'npm publish'
    permissions:
      contents: write
      packages: write
    secrets: inherit
