name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - DOES_NOT_WORK  # TODO: trenger tilgang til secrets: PUBLIC_ACTIONS_LIBRARY_APP_ID and PUBLIC_ACTIONS_LIBRARY_SSH_KEY

permissions:
  contents: write
  packages: write

jobs:
  release-and-publish-mvn:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-maven.yaml@b1509281d74a1afb44d9ceabfb361f8cf4bec420 # v0.3.6
    secrets: inherit
    with:
      java-version: '25'

  publish-npm:
    runs-on: ubuntu-latest
    if: needs.release-and-publish-mvn.outputs.published == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

